version: '3'

tasks:
  default:
    sources:
    - "./**/*.go"
    method: timestamp
    cmds:
    - clear
    - make build
    - ls -lah bin/
    - make tests
    - make lints
  testcase: go test -v -failfast -count=1 -run "TestAll/{{ .Case }}" ./...
